[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "bar-vision-backend"
version = "0.1.0"
description = "Bar Vision FastAPI backend"
requires-python = ">=3.13,<3.14"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic-settings",
    "email-validator",
    "sqlalchemy==2.0.52",
    "asyncpg==0.31.0",
    "alembic==1.19.1",
    "PyJWT==2.10.1",
    "bcrypt==4.3.0",
    "python-multipart==0.0.20",
    "minio==7.2.16"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "httpx"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"